name: guru
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  speech_to_text: ^7.0.0
  openai_api: ^0.3.7
  flutter_dotenv: ^5.2.1

  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - env.txt




